# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: proxy-linux
        path: proxy
        retention-days: 14

  build-mac-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build
      run: env GOARCH=arm64 go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: proxy-darwin-arm64
        path: proxy
        retention-days: 14

  build-mac-amd64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build
      run: env GOARCH=amd64 go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: proxy-darwin-amd64
        path: proxy
        retention-days: 14

  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: proxy-windows.exe
        path: proxy.exe
        retention-days: 14